In [2]:
# Day 6: Start of Numpy Libray

# numpy ( library )-> numerical python ops
# as stands for alias

import numpy as np

In [3]:
# Array in numpy can be -> 1. Scalar 2. Vector 3. Matrix 4. Tensor

# Array in numpy are created by np.array() method

arr = np.array([[1,2,3], [4,5,6], [7,8,9]]) # arr -> ndarray object


In [4]:
# ndarray has attributes like -> shape, ndim, size, dtype, itemsize, T ( e.q: c.shapre, c.ndim, c.size, c.dtype)

# attributes describe what an array is or has.

print(arr.shape) # return dimensions
print(arr.ndim) # return number of dimensions
print(arr.size) # return total numbers elements in an array
print(arr.dtype) # return data type of elements stored in an array
print(arr.itemsize, "Bytes") # return size of item in an array
print(arr.T) # return transpose



(3, 3)
2
9
int64
8 Bytes
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
# Numpy object method

# Methods are functions bound to the object (methods describe what the array does.) :


# Methods that are tied to Class ( like static functions) :
# np.zeros((2, 3))
# np.ones((3, 3))
# np.eye(4)
# np.linspace(0, 1, 5)
# np.concatenate([a, a], axis=0)


